# Generated by Django 5.2.3 on 2025-06-24 03:10

import django.db.models.deletion
import penjualan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBarang', models.CharField(max_length=100)),
                ('deskripsiBarang', models.TextField()),
                ('hargaBarang', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stokBarang', models.IntegerField()),
                ('fotoBarang', models.ImageField(blank=True, null=True, upload_to='foto_barang/')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPelanggan', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggalLahir', models.DateField()),
                ('noHp', models.CharField(max_length=15)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahBarang', models.IntegerField()),
                ('diskon', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.barang')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanPenjualan',
            fields=[
            ],
            options={
                'verbose_name': 'Laporan Penjualan',
                'verbose_name_plural': 'Laporan Penjualan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('penjualan.detailtransaksi',),
        ),
        migrations.CreateModel(
            name='NotifikasiCRM',
            fields=[
            ],
            options={
                'verbose_name': 'Notifikasi CRM',
                'verbose_name_plural': 'Notifikasi CRM',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('penjualan.pelanggan',),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('idTransaksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('statusTransaksi', models.CharField(choices=[('PENDING', 'Pending'), ('SELESAI', 'Selesai'), ('BATAL', 'Batal')], max_length=10)),
                ('buktiBayar', models.ImageField(blank=True, null=True, upload_to=penjualan.models.upload_bukti_path)),
                ('ulasan', models.TextField(blank=True, null=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.pelanggan')),
            ],
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjualan.transaksi'),
        ),
    ]
